# Generated by Django 6.1.1 on 2026-10-01 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('status', models.CharField(choices=[('demanda', 'Demanda'), ('criacao', 'Criação'), ('avaliacao', 'Avaliação'), ('concluido', 'Concluído')], default='demanda', max_length=10, verbose_name='status')),
                ('inicio', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='início')),
                ('prazo', models.DateTimeField(blank=True, null=True, verbose_name='prazo')),
                ('conclusao', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='conclusão')),
                ('versao', models.PositiveBigIntegerField(default=1, editable=False)),
                ('excluida_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.servico', verbose_name='serviço')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='EventoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator_nome', models.CharField(max_length=150)),
                ('instante', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(max_length=15)),
                ('status_anterior', models.CharField(blank=True, max_length=10)),
                ('status_novo', models.CharField(max_length=10)),
                ('alteracoes', models.JSONField(default=dict)),
                ('ator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='tarefas.tarefa')),
            ],
            options={
                'verbose_name': 'evento de tarefa',
                'verbose_name_plural': 'eventos de tarefas',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='tarefa',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['demanda', 'criacao', 'avaliacao', 'concluido'])), name='tarefa_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='tarefa',
            constraint=models.CheckConstraint(condition=models.Q(('versao__gte', 1)), name='tarefa_versao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='tarefa',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'demanda'), ('inicio__isnull', False), _connector='OR'), name='tarefa_inicio_coerente'),
        ),
        migrations.AddConstraint(
            model_name='tarefa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conclusao__isnull', False), ('status', 'concluido')), models.Q(models.Q(('status', 'concluido'), _negated=True), ('conclusao__isnull', True)), _connector='OR'), name='tarefa_conclusao_coerente'),
        ),
    ]
