# Generated by Django 6.1.1 on 2026-10-01 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=15, verbose_name='status')),
            ],
            options={
                'verbose_name': 'equipamento',
                'verbose_name_plural': 'equipamentos',
                'ordering': ['nome', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['disponivel', 'ocupado', 'indisponivel'])), name='equipamento_status_valido')],
            },
        ),
        migrations.CreateModel(
            name='Espaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('capacidade_maxima_de_pessoas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)], verbose_name='capacidade máxima de pessoas')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=15, verbose_name='status')),
            ],
            options={
                'verbose_name': 'espaço',
                'verbose_name_plural': 'espaços',
                'ordering': ['nome', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('capacidade_maxima_de_pessoas__gte', 1), ('capacidade_maxima_de_pessoas__lte', 2147483647)), name='espaco_capacidade_valida'), models.CheckConstraint(condition=models.Q(('status__in', ['disponivel', 'ocupado', 'indisponivel'])), name='espaco_status_valido')],
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=15, verbose_name='status')),
                ('codigo_inicial', models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
                'ordering': ['nome', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['disponivel', 'indisponivel'])), name='servico_status_valido')],
            },
        ),
    ]
