# Generated by Django 6.1.1 on 2026-10-06 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='codigo_inicial',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='espaco',
            name='codigo_inicial',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='espaco',
            name='somente_administradores',
            field=models.BooleanField(default=False, verbose_name='agendamento exclusivo de administradores'),
        ),
        migrations.AlterField(
            model_name='espaco',
            name='capacidade_maxima_de_pessoas',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2147483647)], verbose_name='capacidade máxima de pessoas'),
        ),
    ]
