# Generated by Django 6.1.1 on 2026-10-06 16:06

import catalogo.equipment_photos
from django.db import migrations, models


def seed_photos(apps, schema_editor):
    equipment = apps.get_model('catalogo', 'Equipamento')
    for code, filename in (
        ('plotter-impressao', 'plotter-impressao.png'), ('impressora-3d', 'impressora-3d.png'),
        ('corte-laser', 'corte-laser.png'), ('plotter-corte', 'plotter-corte.png'),
        ('realidade-virtual', 'realidade-virtual.jpg'), ('scanner-3d', 'scanner-3d.jpg'),
    ):
        equipment.objects.using(schema_editor.connection.alias).filter(codigo_inicial=code, foto='').update(
            foto='iniciais/' + filename,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_carga_maquinas_e_espacos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='foto',
            field=models.ImageField(blank=True, storage=catalogo.equipment_photos.EquipmentPhotoStorage(), upload_to='equipamentos/', verbose_name='foto'),
        ),
        migrations.RunPython(seed_photos, migrations.RunPython.noop),
    ]
