# Generated by Django 6.1.1 on 2026-10-02 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requerente', models.CharField(max_length=150)),
                ('motivo', models.TextField()),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('versao', models.PositiveBigIntegerField(default=1, editable=False)),
                ('cancelado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.equipamento')),
                ('espaco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.espaco')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.servico')),
            ],
            options={
                'ordering': ['inicio', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EventoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator_nome', models.CharField(max_length=150)),
                ('instante', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(choices=[('criar', 'Criar'), ('editar', 'Editar'), ('cancelar', 'Cancelar')], max_length=15)),
                ('alteracoes', models.JSONField(default=dict)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='agenda.agendamento')),
                ('ator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['inicio', 'fim'], name='agenda_periodo_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('equipamento__isnull', True), ('espaco__isnull', True), ('servico__isnull', False)), models.Q(('equipamento__isnull', False), ('espaco__isnull', True), ('servico__isnull', True)), models.Q(('equipamento__isnull', True), ('espaco__isnull', False), ('servico__isnull', True)), _connector='OR'), name='agenda_exatamente_um_alvo'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='agenda_intervalo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(('versao__gte', 1)), name='agenda_versao_positiva'),
        ),
    ]
