# Generated by Django 6.1.1 on 2026-10-06 13:01

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('catalogo', '0004_carga_maquinas_e_espacos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='equipamentos',
            field=models.ManyToManyField(blank=True, related_name='agendamentos_de_servico', to='catalogo.equipamento'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='material_gasto_gramas',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='material gasto (g)'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='material_proprio',
            field=models.BooleanField(blank=True, null=True, verbose_name='tem material próprio'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material_gasto_gramas__isnull', True), ('material_proprio__isnull', True)), models.Q(('material_gasto_gramas__isnull', True), ('material_proprio', True), ('servico__isnull', False)), models.Q(('material_gasto_gramas__gt', 0), ('material_proprio', False), ('servico__isnull', False), ('material_gasto_gramas__isnull', False)), _connector='OR'), name='agenda_material_de_servico_valido'),
        ),
    ]
