# Generated by Django 6.1.1 on 2026-10-06 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_formularios_por_categoria'),
        ('catalogo', '0004_carga_maquinas_e_espacos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agendamento',
            name='agenda_material_de_servico_valido',
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material_gasto_gramas__isnull', True), ('material_proprio__isnull', True)), models.Q(('material_gasto_gramas__isnull', True), ('material_proprio', True), ('material_proprio__isnull', False), ('servico__isnull', False)), models.Q(('material_gasto_gramas__gt', 0), ('material_proprio', False), ('material_proprio__isnull', False), ('servico__isnull', False), ('material_gasto_gramas__isnull', False)), _connector='OR'), name='agenda_material_de_servico_valido'),
        ),
    ]
