# Generated by Django 6.1.1 on 2026-10-06 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_valida_material_nao_informado'),
        ('catalogo', '0004_carga_maquinas_e_espacos'),
        ('materiais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='material_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materiais.material', verbose_name='material utilizado'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(('material_gasto__isnull', True), models.Q(('material_proprio', False), ('material_proprio__isnull', False), ('servico__isnull', False)), _connector='OR'), name='agenda_tipo_material_valido'),
        ),
    ]
