# Generated by Django 6.1.1 on 2026-10-06 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agendamento_material_gasto_and_more'),
        ('catalogo', '0004_carga_maquinas_e_espacos'),
        ('materiais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='avaliado_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='avaliado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_avaliados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='situacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('rejeitado', 'Rejeitado')], default='confirmado', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='eventoagendamento',
            name='acao',
            field=models.CharField(choices=[('criar', 'Criar'), ('editar', 'Editar'), ('cancelar', 'Cancelar'), ('aprovar', 'Aprovar'), ('rejeitar', 'Rejeitar')], max_length=15),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(('situacao__in', ['pendente', 'confirmado', 'rejeitado'])), name='agenda_situacao_valida'),
        ),
    ]
