# Generated by Django 6.1.1 on 2026-10-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_agendamento_avaliado_em_agendamento_avaliado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='requerente',
        ),
    ]
