# Generated by Django 6.1.1 on 2026-10-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_remove_agendamento_requerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='observações'),
        ),
    ]
