# Generated by Django 6.1.1 on 2026-10-06 22:17

from django.conf import settings
from django.db import migrations, models


def seed_visit_lock(apps, schema_editor):
    apps.get_model('agenda', 'ControleAgendaVisitas').objects.using(schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_agendamento_observacoes'),
        ('catalogo', '0006_fotos_iniciais_webp'),
        ('materiais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleAgendaVisitas',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RunPython(seed_visit_lock, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='agendamento',
            name='agenda_exatamente_um_alvo',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='visita',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='motivo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('visita', False), models.Q(models.Q(('equipamento__isnull', True), ('espaco__isnull', True), ('servico__isnull', False)), models.Q(('equipamento__isnull', False), ('espaco__isnull', True), ('servico__isnull', True)), models.Q(('equipamento__isnull', True), ('espaco__isnull', False), ('servico__isnull', True)), _connector='OR')), models.Q(('equipamento__isnull', True), ('espaco__isnull', True), ('servico__isnull', True), ('visita', True)), _connector='OR'), name='agenda_exatamente_um_alvo'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(('visita', False), models.Q(('motivo', ''), ('observacoes', '')), _connector='OR'), name='agenda_visita_sem_textos'),
        ),
    ]
