# Generated by Django 6.1.1 on 2026-10-06 23:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_visitas_e_espacos_legados'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaAgroHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origem', models.URLField(editable=False, max_length=2048)),
                ('reserva_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('status_remoto', models.CharField(blank=True, editable=False, max_length=20)),
                ('operacao', models.CharField(default='criar', editable=False, max_length=10)),
                ('estado', models.CharField(choices=[('pendente', 'Envio pendente'), ('enviando', 'Envio em andamento'), ('registrada', 'Enviada ao AgroHub'), ('falha', 'Envio não concluído'), ('incerta', 'Aguardando conciliação')], default='pendente', editable=False, max_length=12)),
                ('payload', models.JSONField(default=dict, editable=False)),
                ('mensagem', models.CharField(blank=True, editable=False, max_length=500)),
                ('ultima_tentativa', models.DateTimeField(blank=True, editable=False, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_agrohub', to='agenda.agendamento')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('origem', 'reserva_id'), name='agrohub_reserva_origem_id_unico')],
            },
        ),
    ]
