# Generated by Django 6.1.1 on 2026-10-07 01:03

import django.core.validators
from django.conf import settings
from django.db import migrations, models


def initialize_visit_people(apps, schema_editor):
    apps.get_model('agenda', 'Agendamento').objects.using(schema_editor.connection.alias).filter(visita=True).update(quantidade_pessoas=1)


def clear_visit_people(apps, schema_editor):
    apps.get_model('agenda', 'Agendamento').objects.using(schema_editor.connection.alias).update(quantidade_pessoas=None)


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_reserva_agrohub'),
        ('catalogo', '0006_fotos_iniciais_webp'),
        ('materiais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='quantidade_pessoas',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade de pessoas'),
        ),
        migrations.RunPython(initialize_visit_people, clear_visit_people),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantidade_pessoas__gte', 1), ('quantidade_pessoas__isnull', False), ('visita', True)), models.Q(('quantidade_pessoas__isnull', True), ('visita', False)), _connector='OR'), name='agenda_quantidade_visita_valida'),
        ),
    ]
