# Generated by Django 6.1.1 on 2026-10-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0011_desvincula_espacos_legados'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaagrohub',
            name='recebida',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
