# Generated by Django 6.1.1 on 2026-10-07 15:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0012_identifica_reservas_recebidas_agrohub'),
        ('catalogo', '0007_remove_espaco'),
        ('materiais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('versao', models.PositiveBigIntegerField(default=1, editable=False)),
                ('cancelado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('rejeitado', 'Rejeitado')], default='confirmado', editable=False, max_length=10)),
                ('avaliado_em', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['inicio', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgendaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('versao', models.PositiveBigIntegerField(default=1, editable=False)),
                ('cancelado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('rejeitado', 'Rejeitado')], default='confirmado', editable=False, max_length=10)),
                ('avaliado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('material_proprio', models.BooleanField(blank=True, null=True, verbose_name='tem material próprio')),
                ('material_gasto_gramas', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='material gasto (g)')),
            ],
            options={
                'ordering': ['inicio', 'pk'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agendaequipamento',
            name='avaliado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_avaliados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendaequipamento',
            name='criado_por',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendaequipamento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.equipamento'),
        ),
        migrations.AddField(
            model_name='eventoagendamento',
            name='agenda_equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='agenda.agendaequipamento'),
        ),
        migrations.AddField(
            model_name='agendaservico',
            name='avaliado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_avaliados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendaservico',
            name='criado_por',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendaservico',
            name='equipamentos',
            field=models.ManyToManyField(blank=True, related_name='agendamentos_de_servico', to='catalogo.equipamento'),
        ),
        migrations.AddField(
            model_name='agendaservico',
            name='material_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='materiais.material', verbose_name='material utilizado'),
        ),
        migrations.AddField(
            model_name='agendaservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.servico'),
        ),
        migrations.AddField(
            model_name='eventoagendamento',
            name='agenda_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='agenda.agendaservico'),
        ),
        migrations.AddIndex(
            model_name='agendaequipamento',
            index=models.Index(fields=['inicio', 'fim'], name='agendaequipamento_periodo_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendaequipamento',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='agendaequipamento_intervalo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='agendaequipamento',
            constraint=models.CheckConstraint(condition=models.Q(('versao__gte', 1)), name='agendaequipamento_versao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='agendaequipamento',
            constraint=models.CheckConstraint(condition=models.Q(('situacao__in', ['pendente', 'confirmado', 'rejeitado'])), name='agendaequipamento_situacao_valida'),
        ),
        migrations.AddIndex(
            model_name='agendaservico',
            index=models.Index(fields=['inicio', 'fim'], name='agendaservico_periodo_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendaservico',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='agendaservico_intervalo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='agendaservico',
            constraint=models.CheckConstraint(condition=models.Q(('versao__gte', 1)), name='agendaservico_versao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='agendaservico',
            constraint=models.CheckConstraint(condition=models.Q(('situacao__in', ['pendente', 'confirmado', 'rejeitado'])), name='agendaservico_situacao_valida'),
        ),
        migrations.AddConstraint(
            model_name='agendaservico',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material_gasto_gramas__isnull', True), ('material_proprio__isnull', True)), models.Q(('material_gasto_gramas__isnull', True), ('material_proprio', True), ('material_proprio__isnull', False)), models.Q(('material_gasto_gramas__gt', 0), ('material_gasto_gramas__isnull', False), ('material_proprio', False), ('material_proprio__isnull', False)), _connector='OR'), name='agendaservico_material_valido'),
        ),
        migrations.AddConstraint(
            model_name='agendaservico',
            constraint=models.CheckConstraint(condition=models.Q(('material_gasto__isnull', True), models.Q(('material_proprio', False), ('material_proprio__isnull', False)), _connector='OR'), name='agendaservico_tipo_material_valido'),
        ),
        migrations.AlterField(model_name='eventoagendamento', name='agendamento', field=models.ForeignKey('agenda.Agendamento', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', null=True))
    ]
