# Generated by Django 6.1.1 on 2026-10-07 18:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_remove_agenda_antiga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('versao', models.PositiveBigIntegerField(default=1, editable=False)),
                ('cancelado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('rejeitado', 'Rejeitado')], default='confirmado', editable=False, max_length=10)),
                ('avaliado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('quantidade_pessoas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
            ],
            options={
                'ordering': ['data', 'hora_inicio', 'pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='eventoagendamento',
            name='evento_exatamente_uma_agenda',
        ),
        migrations.AddField(
            model_name='agendavisita',
            name='avaliado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_avaliados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agendavisita',
            name='criado_por',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoagendamento',
            name='agenda_visita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='agenda.agendavisita'),
        ),
        migrations.AddConstraint(
            model_name='eventoagendamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agenda_equipamento__isnull', True), ('agenda_servico__isnull', False), ('agenda_visita__isnull', True)), models.Q(('agenda_equipamento__isnull', False), ('agenda_servico__isnull', True), ('agenda_visita__isnull', True)), models.Q(('agenda_equipamento__isnull', True), ('agenda_servico__isnull', True), ('agenda_visita__isnull', False)), _connector='OR'), name='evento_exatamente_uma_agenda'),
        ),
        migrations.AddIndex(
            model_name='agendavisita',
            index=models.Index(fields=['data', 'hora_inicio', 'hora_termino'], name='agendavisita_periodo_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendavisita',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_pessoas__gte', 1)), name='agendavisita_pessoas_positivas'),
        ),
        migrations.AddConstraint(
            model_name='agendavisita',
            constraint=models.CheckConstraint(condition=models.Q(('hora_termino__gt', models.F('hora_inicio'))), name='agendavisita_periodo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='agendavisita',
            constraint=models.CheckConstraint(condition=models.Q(('versao__gte', 1)), name='agendavisita_versao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='agendavisita',
            constraint=models.CheckConstraint(condition=models.Q(('situacao__in', ['pendente', 'confirmado', 'rejeitado'])), name='agendavisita_situacao_valida'),
        ),
    ]
