# Generated by Django 6.1.1 on 2026-10-02 23:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('categoria', models.CharField(max_length=100, verbose_name='categoria')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='quantidade')),
                ('unidade', models.CharField(max_length=20, verbose_name='unidade')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=15, verbose_name='status')),
                ('fonte', models.CharField(max_length=150, verbose_name='fonte / origem')),
                ('versao', models.PositiveBigIntegerField(default=1, editable=False, verbose_name='versão')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiais',
                'ordering': ['nome', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gte', 0), ('quantidade__lte', Decimal('999999999.999'))), name='material_quantidade_valida'), models.CheckConstraint(condition=models.Q(('status__in', ['disponivel', 'indisponivel'])), name='material_status_valido'), models.CheckConstraint(condition=models.Q(('versao__gte', 1)), name='material_versao_positiva')],
            },
        ),
    ]
