# Generated by Django 6.1.1 on 2026-10-06 02:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_administrator_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, upload_to=accounts.models.profile_photo_path, verbose_name='foto de perfil'),
        ),
    ]
