# Generated by Django 6.1.1 on 2026-10-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agrohub_foto_url',
            field=models.URLField(blank=True, editable=False, max_length=2048),
        ),
        migrations.AddField(
            model_name='user',
            name='agrohub_id',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='agrohub_username',
            field=models.CharField(blank=True, editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
