# Generated by Django 6.1.1 on 2026-10-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_identidade_agrohub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agrohub_roles',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
