# Generated by Django 6.1.1 on 2026-10-02 23:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('token_digest', models.CharField(blank=True, editable=False, max_length=64)),
                ('versao', models.PositiveBigIntegerField(default=1, editable=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PedidoIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.CharField(max_length=150)),
                ('requerente_id', models.CharField(max_length=150)),
                ('conteudo_digest', models.CharField(editable=False, max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_integracao', to='agenda.agendamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='integracoes.clienteintegracao')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='clienteintegracao',
            constraint=models.CheckConstraint(condition=models.Q(('versao__gte', 1)), name='integracoes_versao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='pedidointegracao',
            constraint=models.UniqueConstraint(fields=('cliente', 'id_externo'), name='integracoes_pedido_unico'),
        ),
    ]
