# Generated by Django 6.1.1 on 2026-10-07 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_agendaequipamento_agendaservico_and_more'),
        ('integracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidointegracao',
            name='agenda_equipamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_integracao', to='agenda.agendaequipamento'),
        ),
        migrations.AddField(
            model_name='pedidointegracao',
            name='agenda_servico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedido_integracao', to='agenda.agendaservico'),
        ),
        migrations.AlterField(model_name='pedidointegracao', name='agendamento', field=models.OneToOneField('agenda.Agendamento', on_delete=django.db.models.deletion.PROTECT, related_name='pedido_integracao', null=True))
    ]
