# Generated by Django 6.1.1 on 2026-10-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('texto_alternativo', models.CharField(blank=True, max_length=250, verbose_name='texto alternativo')),
                ('banner_img', models.ImageField(upload_to='banners/', verbose_name='imagem WebP')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('agendado', 'Agendado')], default='inativo', max_length=8, verbose_name='status')),
                ('local', models.CharField(choices=[('home', 'Início'), ('sobre', 'Sobre')], default='home', max_length=5, verbose_name='local')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('inicio_exibicao', models.DateTimeField(blank=True, null=True, verbose_name='início da exibição')),
                ('fim_exibicao', models.DateTimeField(blank=True, null=True, verbose_name='fim da exibição')),
                ('versao', models.PositiveBigIntegerField(default=1, editable=False, verbose_name='versão')),
                ('excluido_em', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ['ordem', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['ativo', 'inativo', 'agendado'])), name='banner_status_valido'), models.CheckConstraint(condition=models.Q(('local__in', ['home', 'sobre'])), name='banner_local_valido'), models.CheckConstraint(condition=models.Q(('ordem__gte', 0), ('ordem__lte', 2147483647)), name='banner_ordem_valida'), models.CheckConstraint(condition=models.Q(('versao__gte', 1)), name='banner_versao_positiva'), models.CheckConstraint(condition=models.Q(models.Q(('fim_exibicao__gt', models.F('inicio_exibicao')), ('fim_exibicao__isnull', False), ('inicio_exibicao__isnull', False), ('status', 'agendado')), models.Q(('fim_exibicao__isnull', True), ('inicio_exibicao__isnull', True), ('status__in', ['ativo', 'inativo'])), _connector='OR'), name='banner_periodo_valido')],
            },
        ),
    ]
