# Generated by Django 6.1.1 on 2026-10-07 23:17

import django.core.validators
import django.db.models.deletion
import inovalab_app.catalogo.equipment_photos
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('versao', models.PositiveBigIntegerField(default=1, editable=False)),
                ('cancelado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('rejeitado', 'Rejeitado')], default='confirmado', editable=False, max_length=10)),
                ('avaliado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('quantidade_pessoas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('avaliado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_avaliados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agenda_agendavisita',
                'ordering': ['data', 'hora_inicio', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('texto_alternativo', models.CharField(blank=True, max_length=250, verbose_name='texto alternativo')),
                ('banner_img', models.ImageField(upload_to='banners/', verbose_name='imagem WebP')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('agendado', 'Agendado')], default='inativo', max_length=8, verbose_name='status')),
                ('local', models.CharField(choices=[('home', 'Início'), ('sobre', 'Sobre')], default='home', max_length=5, verbose_name='local')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('inicio_exibicao', models.DateTimeField(blank=True, null=True, verbose_name='início da exibição')),
                ('fim_exibicao', models.DateTimeField(blank=True, null=True, verbose_name='fim da exibição')),
                ('versao', models.PositiveBigIntegerField(default=1, editable=False, verbose_name='versão')),
                ('excluido_em', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'db_table': 'conteudo_banner',
                'ordering': ['ordem', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['ativo', 'inativo', 'agendado'])), name='banner_status_valido'), models.CheckConstraint(condition=models.Q(('local__in', ['home', 'sobre'])), name='banner_local_valido'), models.CheckConstraint(condition=models.Q(('ordem__gte', 0), ('ordem__lte', 2147483647)), name='banner_ordem_valida'), models.CheckConstraint(condition=models.Q(('versao__gte', 1)), name='banner_versao_positiva'), models.CheckConstraint(condition=models.Q(models.Q(('fim_exibicao__gt', models.F('inicio_exibicao')), ('fim_exibicao__isnull', False), ('inicio_exibicao__isnull', False), ('status', 'agendado')), models.Q(('fim_exibicao__isnull', True), ('inicio_exibicao__isnull', True), ('status__in', ['ativo', 'inativo'])), _connector='OR'), name='banner_periodo_valido')],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('codigo_inicial', models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True)),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('foto', models.ImageField(blank=True, storage=inovalab_app.catalogo.equipment_photos.EquipmentPhotoStorage(), upload_to='equipamentos/', verbose_name='foto')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('ocupado', 'Ocupado'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=15, verbose_name='status')),
            ],
            options={
                'verbose_name': 'equipamento',
                'verbose_name_plural': 'equipamentos',
                'db_table': 'catalogo_equipamento',
                'ordering': ['nome', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['disponivel', 'ocupado', 'indisponivel'])), name='equipamento_status_valido')],
            },
        ),
        migrations.CreateModel(
            name='AgendaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('versao', models.PositiveBigIntegerField(default=1, editable=False)),
                ('cancelado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('rejeitado', 'Rejeitado')], default='confirmado', editable=False, max_length=10)),
                ('avaliado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('motivo', models.TextField(blank=True, default='')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('material_proprio', models.BooleanField(blank=True, null=True, verbose_name='tem material próprio')),
                ('material_gasto_gramas', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='material gasto (g)')),
                ('avaliado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_avaliados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('equipamentos', models.ManyToManyField(blank=True, db_table='agenda_agendaservico_equipamentos', related_name='agendamentos_de_servico', to='inovalab_app.equipamento')),
            ],
            options={
                'db_table': 'agenda_agendaservico',
                'ordering': ['inicio', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgendaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='observações')),
                ('versao', models.PositiveBigIntegerField(default=1, editable=False)),
                ('cancelado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('situacao', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('rejeitado', 'Rejeitado')], default='confirmado', editable=False, max_length=10)),
                ('avaliado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('motivo', models.TextField(blank=True, default='')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('avaliado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_avaliados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inovalab_app.equipamento')),
            ],
            options={
                'db_table': 'agenda_agendaequipamento',
                'ordering': ['inicio', 'pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator_nome', models.CharField(max_length=150)),
                ('instante', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(choices=[('criar', 'Criar'), ('editar', 'Editar'), ('cancelar', 'Cancelar'), ('aprovar', 'Aprovar'), ('rejeitar', 'Rejeitar')], max_length=15)),
                ('alteracoes', models.JSONField(default=dict)),
                ('agenda_equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='inovalab_app.agendaequipamento')),
                ('agenda_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='inovalab_app.agendaservico')),
                ('agenda_visita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='inovalab_app.agendavisita')),
                ('ator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agenda_eventoagendamento',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('categoria', models.CharField(max_length=100, verbose_name='categoria')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='quantidade')),
                ('unidade', models.CharField(max_length=20, verbose_name='unidade')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=15, verbose_name='status')),
                ('fonte', models.CharField(max_length=150, verbose_name='fonte / origem')),
                ('versao', models.PositiveBigIntegerField(default=1, editable=False, verbose_name='versão')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiais',
                'db_table': 'materiais_material',
                'ordering': ['nome', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gte', 0), ('quantidade__lte', Decimal('999999999.999'))), name='material_quantidade_valida'), models.CheckConstraint(condition=models.Q(('status__in', ['disponivel', 'indisponivel'])), name='material_status_valido'), models.CheckConstraint(condition=models.Q(('versao__gte', 1)), name='material_versao_positiva')],
            },
        ),
        migrations.AddField(
            model_name='agendaservico',
            name='material_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inovalab_app.material', verbose_name='material utilizado'),
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=15, verbose_name='status')),
                ('codigo_inicial', models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
                'db_table': 'catalogo_servico',
                'ordering': ['nome', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['disponivel', 'indisponivel'])), name='servico_status_valido')],
            },
        ),
        migrations.AddField(
            model_name='agendaservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inovalab_app.servico'),
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('status', models.CharField(choices=[('demanda', 'Demanda'), ('criacao', 'Criação'), ('avaliacao', 'Avaliação'), ('concluido', 'Concluído')], default='demanda', max_length=10, verbose_name='status')),
                ('inicio', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='início')),
                ('prazo', models.DateTimeField(blank=True, null=True, verbose_name='prazo')),
                ('conclusao', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='conclusão')),
                ('versao', models.PositiveBigIntegerField(default=1, editable=False)),
                ('excluida_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inovalab_app.servico', verbose_name='serviço')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'db_table': 'tarefas_tarefa',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='EventoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator_nome', models.CharField(max_length=150)),
                ('instante', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(max_length=15)),
                ('status_anterior', models.CharField(blank=True, max_length=10)),
                ('status_novo', models.CharField(max_length=10)),
                ('alteracoes', models.JSONField(default=dict)),
                ('ator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='inovalab_app.tarefa')),
            ],
            options={
                'verbose_name': 'evento de tarefa',
                'verbose_name_plural': 'eventos de tarefas',
                'db_table': 'tarefas_eventotarefa',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='agendavisita',
            index=models.Index(fields=['data', 'hora_inicio', 'hora_termino'], name='agendavisita_periodo_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendavisita',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_pessoas__gte', 1)), name='agendavisita_pessoas_positivas'),
        ),
        migrations.AddConstraint(
            model_name='agendavisita',
            constraint=models.CheckConstraint(condition=models.Q(('hora_termino__gt', models.F('hora_inicio'))), name='agendavisita_periodo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='agendavisita',
            constraint=models.CheckConstraint(condition=models.Q(('versao__gte', 1)), name='agendavisita_versao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='agendavisita',
            constraint=models.CheckConstraint(condition=models.Q(('situacao__in', ['pendente', 'confirmado', 'rejeitado'])), name='agendavisita_situacao_valida'),
        ),
        migrations.AddIndex(
            model_name='agendaequipamento',
            index=models.Index(fields=['inicio', 'fim'], name='agendaequipamento_periodo_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendaequipamento',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='agendaequipamento_intervalo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='agendaequipamento',
            constraint=models.CheckConstraint(condition=models.Q(('versao__gte', 1)), name='agendaequipamento_versao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='agendaequipamento',
            constraint=models.CheckConstraint(condition=models.Q(('situacao__in', ['pendente', 'confirmado', 'rejeitado'])), name='agendaequipamento_situacao_valida'),
        ),
        migrations.AddConstraint(
            model_name='eventoagendamento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agenda_equipamento__isnull', True), ('agenda_servico__isnull', False), ('agenda_visita__isnull', True)), models.Q(('agenda_equipamento__isnull', False), ('agenda_servico__isnull', True), ('agenda_visita__isnull', True)), models.Q(('agenda_equipamento__isnull', True), ('agenda_servico__isnull', True), ('agenda_visita__isnull', False)), _connector='OR'), name='evento_exatamente_uma_agenda'),
        ),
        migrations.AddIndex(
            model_name='agendaservico',
            index=models.Index(fields=['inicio', 'fim'], name='agendaservico_periodo_idx'),
        ),
        migrations.AddConstraint(
            model_name='agendaservico',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='agendaservico_intervalo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='agendaservico',
            constraint=models.CheckConstraint(condition=models.Q(('versao__gte', 1)), name='agendaservico_versao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='agendaservico',
            constraint=models.CheckConstraint(condition=models.Q(('situacao__in', ['pendente', 'confirmado', 'rejeitado'])), name='agendaservico_situacao_valida'),
        ),
        migrations.AddConstraint(
            model_name='agendaservico',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material_gasto_gramas__isnull', True), ('material_proprio__isnull', True)), models.Q(('material_gasto_gramas__isnull', True), ('material_proprio', True), ('material_proprio__isnull', False)), models.Q(('material_gasto_gramas__gt', 0), ('material_gasto_gramas__isnull', False), ('material_proprio', False), ('material_proprio__isnull', False)), _connector='OR'), name='agendaservico_material_valido'),
        ),
        migrations.AddConstraint(
            model_name='agendaservico',
            constraint=models.CheckConstraint(condition=models.Q(('material_gasto__isnull', True), models.Q(('material_proprio', False), ('material_proprio__isnull', False)), _connector='OR'), name='agendaservico_tipo_material_valido'),
        ),
        migrations.AddConstraint(
            model_name='tarefa',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['demanda', 'criacao', 'avaliacao', 'concluido'])), name='tarefa_status_valido'),
        ),
        migrations.AddConstraint(
            model_name='tarefa',
            constraint=models.CheckConstraint(condition=models.Q(('versao__gte', 1)), name='tarefa_versao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='tarefa',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'demanda'), ('inicio__isnull', False), _connector='OR'), name='tarefa_inicio_coerente'),
        ),
        migrations.AddConstraint(
            model_name='tarefa',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conclusao__isnull', False), ('status', 'concluido')), models.Q(models.Q(('status', 'concluido'), _negated=True), ('conclusao__isnull', True)), _connector='OR'), name='tarefa_conclusao_coerente'),
        ),
    ]
