# Generated by Django 6.1.1 on 2026-10-08 17:25

import django.db.models.deletion
from django.db import migrations, models


def individualize_services(apps, schema_editor):
    alias = schema_editor.connection.alias
    Service = apps.get_model('inovalab_app', 'Servico')
    Booking = apps.get_model('inovalab_app', 'AgendaServico')
    for booking in Booking.objects.using(alias).select_related('servico_legado').order_by('pk').iterator():
        legacy = booking.servico_legado
        service = Service.objects.using(alias).create(
            titulo=legacy.nome, descricao=booking.motivo_legado or legacy.descricao or legacy.nome,
            prazo=booking.fim_legado,
        )
        Booking.objects.using(alias).filter(pk=booking.pk).update(servico_id=service.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('inovalab_app', '0002_preserva_contenttypes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servico',
            new_name='ServicoLegado',
        ),
        migrations.RemoveConstraint(
            model_name='agendaservico',
            name='agendaservico_intervalo_positivo',
        ),
        migrations.RemoveIndex(
            model_name='agendaservico',
            name='agendaservico_periodo_idx',
        ),
        migrations.RenameField(
            model_name='agendaservico',
            old_name='servico',
            new_name='servico_legado',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='servico',
            new_name='servico_legado',
        ),
        migrations.RenameField(
            model_name='agendaservico',
            old_name='inicio',
            new_name='inicio_legado',
        ),
        migrations.RenameField(
            model_name='agendaservico',
            old_name='fim',
            new_name='fim_legado',
        ),
        migrations.RenameField(
            model_name='agendaservico',
            old_name='motivo',
            new_name='motivo_legado',
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('prazo', models.DateTimeField(verbose_name='prazo')),
            ],
            options={
                'verbose_name': 'serviço solicitado',
                'verbose_name_plural': 'serviços solicitados',
                'db_table': 'inovalab_servico_solicitado',
                'ordering': ['titulo', 'pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='agendaservico',
            options={'ordering': ['servico__prazo', 'pk']},
        ),
        migrations.AddField(
            model_name='equipamento',
            name='excluido_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='agendamento_servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='inovalab_app.agendaservico', verbose_name='agendamento de serviço'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inovalab_app.equipamento', verbose_name='equipamento'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='material_gasto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inovalab_app.material', verbose_name='material gasto'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='quantidade_material_gasto',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='quantidade de material gasto'),
        ),
        migrations.AlterField(
            model_name='agendaservico',
            name='fim_legado',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='agendaservico',
            name='inicio_legado',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='agendaservico',
            name='motivo_legado',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='agendaservico',
            name='servico_legado',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='inovalab_app.servicolegado'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='servico_legado',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='inovalab_app.servicolegado'),
        ),
        migrations.AddField(
            model_name='agendaservico',
            name='servico',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamento', to='inovalab_app.servico'),
        ),
        migrations.RunPython(individualize_services, migrations.RunPython.noop),
    ]
