# Generated by Django 6.1.1 on 2026-10-08 17:25

import django.db.models.deletion
from django.db import migrations, models


def require_task_links(apps, schema_editor):
    Task = apps.get_model('inovalab_app', 'Tarefa')
    ids = list(Task.objects.using(schema_editor.connection.alias).filter(
        agendamento_servico__isnull=True).order_by('pk').values_list('pk', flat=True))
    if ids:
        raise RuntimeError('Tarefas sem agendamento de serviço: ' + ', '.join(map(str, ids)) +
            '. Aplique migrate inovalab_app 0003 e vincular_tarefas_servicos --mapa arquivo.json antes de migrate.')


class Migration(migrations.Migration):

    dependencies = [
        ('inovalab_app', '0003_prepara_servicos_solicitados'),
    ]

    operations = [
        migrations.RunPython(require_task_links, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='agendaservico',
            name='servico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agendamento', to='inovalab_app.servico'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='agendamento_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarefas', to='inovalab_app.agendaservico', verbose_name='agendamento de serviço'),
        ),
    ]
