# Generated by Django 6.1.1 on 2026-10-08 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_existing_links(apps, schema_editor):
    alias = schema_editor.connection.alias
    Task = apps.get_model('inovalab_app', 'Tarefa')
    Responsible = apps.get_model('inovalab_app', 'TarefaResponsavel')
    Equipment = apps.get_model('inovalab_app', 'TarefaEquipamento')
    Material = apps.get_model('inovalab_app', 'TarefaMaterial')
    for task in Task.objects.using(alias).all().iterator(chunk_size=500):
        Responsible.objects.using(alias).create(tarefa_id=task.pk, responsavel_id=task.responsavel_id)
        if task.equipamento_id is not None:
            Equipment.objects.using(alias).create(tarefa_id=task.pk, equipamento_id=task.equipamento_id)
        if task.material_gasto_id is not None:
            Material.objects.using(alias).create(tarefa_id=task.pk, material_id=task.material_gasto_id,
                                                quantidade=task.quantidade_material_gasto)


class Migration(migrations.Migration):

    dependencies = [
        ('inovalab_app', '0005_tarefa_prazo_do_servico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inovalab_app.equipamento')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_equipamentos', to='inovalab_app.tarefa')),
            ],
            options={
                'db_table': 'tarefas_equipamento',
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='equipamentos',
            field=models.ManyToManyField(blank=True, related_name='tarefas_associadas', through='inovalab_app.TarefaEquipamento', to='inovalab_app.equipamento', verbose_name='equipamentos'),
        ),
        migrations.CreateModel(
            name='TarefaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(blank=True, default='', max_length=150, verbose_name='quantidade gasta')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inovalab_app.material')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_gastos', to='inovalab_app.tarefa')),
            ],
            options={
                'db_table': 'tarefas_material',
                'ordering': ['material_id'],
            },
        ),
        migrations.CreateModel(
            name='TarefaResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_responsaveis', to='inovalab_app.tarefa')),
            ],
            options={
                'db_table': 'tarefas_responsavel',
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='responsaveis',
            field=models.ManyToManyField(related_name='tarefas_atribuidas', through='inovalab_app.TarefaResponsavel', to=settings.AUTH_USER_MODEL, verbose_name='responsáveis'),
        ),
        migrations.AddConstraint(
            model_name='tarefaequipamento',
            constraint=models.UniqueConstraint(fields=('tarefa', 'equipamento'), name='tarefa_equipamento_unico'),
        ),
        migrations.AddConstraint(
            model_name='tarefamaterial',
            constraint=models.UniqueConstraint(fields=('tarefa', 'material'), name='tarefa_material_unico'),
        ),
        migrations.AddConstraint(
            model_name='tarefaresponsavel',
            constraint=models.UniqueConstraint(fields=('tarefa', 'responsavel'), name='tarefa_responsavel_unico'),
        ),
        migrations.RunPython(copy_existing_links, migrations.RunPython.noop),
    ]
