# Generated by Django 6.1.1 on 2026-10-09 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inovalab_app', '0006_tarefas_multiplos_vinculos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendavisita',
            name='realizada_em',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='agendavisita',
            name='realizada_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventoagendamento',
            name='acao',
            field=models.CharField(choices=[('criar', 'Criar'), ('editar', 'Editar'), ('cancelar', 'Cancelar'), ('aprovar', 'Aprovar'), ('rejeitar', 'Rejeitar'), ('realizar', 'Realizar')], max_length=15),
        ),
    ]
