"""
Django settings for setup project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

from setup.environment import read_database, read_environment

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Variáveis do processo prevalecem; arquivos locais nunca entram no deploy.
ON_VERCEL = os.environ.get('VERCEL') == '1'
if not ON_VERCEL:
    load_dotenv(BASE_DIR / '.env.local', override=False)
    load_dotenv(BASE_DIR / '.env', override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
RUNTIME = read_environment(os.environ)
SECRET_KEY = RUNTIME.secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = RUNTIME.debug

ALLOWED_HOSTS = list(RUNTIME.allowed_hosts)

CSRF_TRUSTED_ORIGINS = [
    value.strip() for value in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if value.strip()
]
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
if ON_VERCEL:
    # A Vercel encerra TLS e define este cabeçalho no proxy.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core',
    'accounts.apps.AccountsConfig',
    'catalogo.apps.CatalogoConfig',
    'tarefas.apps.TarefasConfig',
    'agenda.apps.AgendaConfig',
    'integracoes.apps.IntegracoesConfig',
    'materiais.apps.MateriaisConfig',
    'conteudo.apps.ConteudoConfig',
]

AUTH_USER_MODEL = 'accounts.User'
AUTHENTICATION_BACKENDS = ['accounts.backends.AgroHubBackend']
AGROHUB_API_BASE_URL = os.environ.get('AGROHUB_API_BASE_URL', 'https://agrohub.unirv.edu.br/api/v1/')
AGROHUB_API_TIMEOUT = 10
AGROHUB_MIN_ADVANCE_NOTICE_HOURS = int(os.environ.get('AGROHUB_MIN_ADVANCE_NOTICE_HOURS', '2'))
AGROHUB_PHOTO_ALLOWED_HOSTS = tuple(value.strip() for value in os.environ.get('AGROHUB_PHOTO_ALLOWED_HOSTS', '').split(',') if value.strip())
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = '/index/'
LOGOUT_REDIRECT_URL = 'conteudo:inicio'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.AgroHubSessionMiddleware',
    'accounts.middleware.InternalAccessMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.navigation.panel_navigation',
            ],
        },
    },
]

WSGI_APPLICATION = 'setup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {'default': read_database(os.environ, BASE_DIR)}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
    },
}
if not DEBUG:
    MAILERS['default']['OPTIONS'] = {
        'host': os.environ.get('DJANGO_EMAIL_HOST') or 'localhost',
        'port': int(os.environ.get('DJANGO_EMAIL_PORT') or '587'),
        'username': os.environ.get('DJANGO_EMAIL_USER', ''),
        'password': os.environ.get('DJANGO_EMAIL_PASSWORD', ''),
        'use_tls': True,
        'timeout': 15,
    }
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', 'webmaster@localhost')
